server:
  port: 8110


spring:
  profiles:
    active: dev
  application:
    name: service-edu
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/guli_edu?serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd
#mybatis日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
